export const SkillList = {
    "skills": {
      "Development": [
        "Javascript",
        "Typescript",
        "React",
        "Angular",
        "Next",
        "Node",
        "Nest",
        "Python",
        "Flask",
        "Django",
        "PHP",
        "Laravel",
        "Symfony",
        "Ruby",
        "Ruby on Rails",
        "Golang",
        "Java",
        "C#",
        ".NET",
        "iOS",
        "Swift",
        "Android",
        "Kotlin",
        "React Native",
        "Flutter",
        "C",
        "C++",
        "Rust",
        "Scala",
        "DevOps",
        "Firebase",
        "Kubernetes",
        "Terraform",
        "Docker",
        "AWS",
        "Azure",
        "Google Cloud Platform",
        "SQL Databases",
        "MongoDB",
        "DynamoDB",
        "Elasticsearch",
        "Développement Salesforce",
        "Web3",
        "Cybersécurité",
        "Hardware",
        "Test & QA"
      ],
      "No-code": [
        "Webflow",
        "Bubble",
        "Wordpress",
        "Strapi",
        "Other CMS",
        "Shopify",
        "Prestashop",
        "Other e-commerce CMS",
        "FlutterFlow",
        "Make",
        "n8n",
        "Airtable",
        "Notion"
      ],
      "Design & Produit": [
        "Product Design - UX/UI",
        "Stratégie Produit",
        "Product Management",
        "Product Ownership",
        "Product Marketing",
        "User Research"
      ],
      "Data": [
        "Data Analysis",
        "Data Visualization",
        "SQL",
        "Metabase",
        "Power BI",
        "Tableau",
        "Looker",
        "Data Science",
        "Machine Learning",
        "Deep Learning",
        "Data Mining",
        "Business Intelligence",
        "IA",
        "Big Data",
        "Natural Language Processing",
        "Computer Vision",
        "Data Governance",
        "Data Privacy",
        "Data Security",
        "ETL",
        "dbt",
        "Scraping"
      ],
      "Marketing & Sales": [
        "Stratégie Marketing",
        "Web Design",
        "CRO",
        "SEO",
        "SEA",
        "Social Media",
        "Email Marketing",
        "Content Marketing",
        "Growth Hacking",
        "Sales",
        "Business Development",
        "Partnerships",
        "Affiliation",
        "CRM",
        "Marketing Automation",
        "Customer Success",
        "Customer Support",
        "Community Management",
        "Inbound Marketing",
        "Outbound Marketing",
        "Lead Generation",
        "Web Analytics",
        "Salesforce",
        "Other CRM"
      ]
    }
  }