export enum MissionStatus {
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    PROVISIONED = 'PROVISIONED',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED',
    CANCELLED = 'CANCELLED',
}