name: Server build pipelines

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: .
        run: docker build . -f Dockerfile -t linker-api:$(date +%s)
